In [3]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes.csv')
df.head()

class  Number of times pregnant  \
0      0                      0.01   
1      0                      0.01   
2      0                      0.05   
3      0                      0.10   
4      0                      0.04   

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                              0.085                          
1                                              0.089                          
2                                              0.116                          
3                                              0.115                          
4                                              0.110                          

   Diastolic blood pressure   Triceps skin fold thickness  \
0                     0.066                          0.29   
1                     0.066                          0.23   
2                     0.074                          0.00   
3                     0.000                          0.00   
4                     0.092                          0.00   

   2 Hour serum insulin  Body mass index  Diabetes pedigree function  \
0                 0.000            0.266                      0.0351   
1                 0.094            0.281                      0.0167   
2                 0.000            0.256                      0.0201   
3                 0.000            0.353                      0.0134   
4                 0.000            0.376                      0.0191   

    Age (years)  
0          0.31  
1          0.21  
2          0.30  
3          0.29  
4          0.30

In [9]:
X = df.drop('class', axis=1)
X = X.values
X

array([[ 0.01  ,  0.085 ,  0.066 , ...,  0.266 ,  0.0351,  0.31  ],
       [ 0.01  ,  0.089 ,  0.066 , ...,  0.281 ,  0.0167,  0.21  ],
       [ 0.05  ,  0.116 ,  0.074 , ...,  0.256 ,  0.0201,  0.3   ],
       ..., 
       [ 0.06  ,  0.19  ,  0.092 , ...,  0.355 ,  0.0278,  0.66  ],
       [ 0.09  ,  0.17  ,  0.074 , ...,  0.44  ,  0.0403,  0.43  ],
       [ 0.01  ,  0.126 ,  0.06  , ...,  0.301 ,  0.0349,  0.47  ]])

In [11]:
Y = df['class']
Y = Y.values
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [12]:
randomForest = RandomForestClassifier()
randomForest.fit(X,Y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [22]:
randomForest.predict(X[len(X)-1])

//anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])